// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://lafbingsygaxtcsqeirv.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZmJpbmdzeWdheHRjc3FlaXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjY2NzY5MDcsImV4cCI6MjA0MjI1MjkwN30.2eUifJ4afBW6sKpvCQzCGSIEiJhmx-4LfolWOg_zCns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);